import bpy
op = bpy.context.active_operator

op.random_seed = 1018
op.amount = 11
op.min_extrude = 0.5
op.max_extrude = 1.0
op.min_taper = 0.5
op.max_taper = 1.0
op.min_rotation = 0.0
op.max_rotation = 0.0
op.min_slide = 0.0
op.max_slide = 0.10000000149011612
op.favour_vec = (0.20000000298023224, 1.0, 0.20000000298023224)
op.mirror_x = True
op.mirror_y = False
op.mirror_z = False
op.is_bevel = True
op.bevel_width = 10.0
op.bevel_profile = 0.5
op.bevel_method = 'PERCENT'
op.bevel_segments = 1
op.bevel_clamp_overlap = False
op.is_subsurf = False
op.subsurf_type = 'CATMULL_CLARK'
op.is_adaptive = False
op.adaptive_dicing = 1.0
op.subsurf_subdivisions = 2
op.subdivide_edges = 0
op.shade_smooth = False
op.auto_smooth = False
op.flip_normals = False
op.prevent_ovelapping_faces = True
op.overlap_check_limit = 0
op.align = 'WORLD'
op.location = (0.0, 0.0, 0.0)
op.rotation = (0.0, -0.0, 0.0)
op.scale = (1.0, 3.1399998664855957, 1.0)
op.random_transform_seed = 12345
op.number_to_create = 1
op.randomize_location = False
op.randomize_rotation = False
op.randomize_scale = False
op.start_rand_location = (0.0, 0.0, 0.0)
op.start_rand_rotation = (0.0, 0.0, 0.0)
op.start_rand_scale = (1.0, 1.0, 1.0)
op.end_rand_location = (0.0, 0.0, 0.0)
op.end_rand_rotation = (0.0, 0.0, 0.0)
op.end_rand_scale = (1.0, 1.0, 1.0)
op.uv_projection_limit = 66.0
op.uv_island_margin = 0.0
op.uv_area_weight = 0.0
op.uv_stretch_to_bounds = True
op.material_to_use = ''
op.is_boolean = False
op.is_parent_booleans = True
op.boolean_main_obj_index = 0
op.main_obj_bool_operation = 'DIFFERENCE'
op.bool_solver = 'EXACT'
op.fast_overlap_threshold = 9.999999974752427e-07
op.exact_self = False
op.bool_hide_viewport = False
op.bool_hide_render = True
op.bool_display_type = 'WIRE'
op.big_random_seed = 0
op.medium_random_seed = 1
op.small_random_seed = 2
op.big_random_scatter_seed = 0
op.medium_random_scatter_seed = 0
op.small_random_scatter_seed = 0
op.big_shape_num = 0
op.medium_shape_num = 0
op.small_shape_num = 0
op.big_shape_scale = 1.0
op.medium_shape_scale = 0.5
op.small_shape_scale = 0.25
op.use_medium_shape_bool = False
op.medium_shape_bool_operation = 'DIFFERENCE'
op.use_small_shape_bool = False
op.small_shape_bool_operation = 'DIFFERENCE'
op.use_colors = False
op.big_shape_color = (0.0, 0.0, 1.0, 1.0)
op.medium_shape_color = (1.0, 1.0, 0.0, 1.0)
op.small_shape_color = (1.0, 0.0, 0.0, 1.0)
